export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

//because it is promise, it is going to have 3 states:
export const REQUEST_ROBOTS_PENDING = "REQUEST_ROBOTS_PENDING";
export const REQUEST_ROBOTS_SUCCESS = "REQUEST_ROBOTS_SUCCESS";
export const REQUEST_ROBOTS_FAILED = "REQUEST_ROBOTS_FAILED";
